CREATE TABLE "fequest_feature_request" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "fequest_feature_request_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"productId" integer NOT NULL,
	"userId" varchar(255) NOT NULL,
	"status" varchar(32) DEFAULT 'pending' NOT NULL,
	"content" text NOT NULL,
	"likes" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "fequest_product" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "fequest_product_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"userId" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "fequest_feature_request" ADD CONSTRAINT "fequest_feature_request_productId_fequest_product_id_fk" FOREIGN KEY ("productId") REFERENCES "public"."fequest_product"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fequest_feature_request" ADD CONSTRAINT "fequest_feature_request_userId_fequest_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."fequest_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fequest_product" ADD CONSTRAINT "fequest_product_userId_fequest_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."fequest_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "fe_feature_request_product_id_idx" ON "fequest_feature_request" USING btree ("productId");--> statement-breakpoint
CREATE INDEX "fe_feature_request_user_id_idx" ON "fequest_feature_request" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "fe_product_user_id_idx" ON "fequest_product" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "fe_product_name_idx" ON "fequest_product" USING btree ("name");