CREATE TABLE "fequest_feature_request_reaction" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "fequest_feature_request_reaction_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"featureRequestId" integer NOT NULL,
	"userId" varchar(255),
	"anonymousIdentifier" varchar(255),
	"emoji" varchar(32) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "fe_feature_request_reaction_identity_check" CHECK ("fequest_feature_request_reaction"."userId" is not null or "fequest_feature_request_reaction"."anonymousIdentifier" is not null)
);
--> statement-breakpoint
ALTER TABLE "fequest_feature_request" DROP CONSTRAINT "fequest_feature_request_userId_fequest_user_id_fk";
--> statement-breakpoint
ALTER TABLE "fequest_feature_request" ALTER COLUMN "userId" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "fequest_feature_request" ALTER COLUMN "status" SET DEFAULT 'open';--> statement-breakpoint
ALTER TABLE "fequest_feature_request_reaction" ADD CONSTRAINT "fequest_feature_request_reaction_featureRequestId_fequest_feature_request_id_fk" FOREIGN KEY ("featureRequestId") REFERENCES "public"."fequest_feature_request"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fequest_feature_request_reaction" ADD CONSTRAINT "fequest_feature_request_reaction_userId_fequest_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."fequest_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "fe_feature_request_reaction_feature_request_id_idx" ON "fequest_feature_request_reaction" USING btree ("featureRequestId");--> statement-breakpoint
CREATE INDEX "fe_feature_request_reaction_user_id_idx" ON "fequest_feature_request_reaction" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "fe_feature_request_reaction_anonymous_identifier_idx" ON "fequest_feature_request_reaction" USING btree ("anonymousIdentifier");--> statement-breakpoint
CREATE UNIQUE INDEX "fe_feature_request_reaction_user_unique" ON "fequest_feature_request_reaction" USING btree ("featureRequestId","userId","emoji");--> statement-breakpoint
CREATE UNIQUE INDEX "fe_feature_request_reaction_anonymous_unique" ON "fequest_feature_request_reaction" USING btree ("featureRequestId","anonymousIdentifier","emoji");--> statement-breakpoint
ALTER TABLE "fequest_feature_request" ADD CONSTRAINT "fequest_feature_request_userId_fequest_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."fequest_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fequest_feature_request" DROP COLUMN "likes";